/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SDG2USD } from "./SDG2USD";
export type { SDGI } from "./SDGI";
export type { USDT } from "./USDT";
